name: CrystalCavernsDungeons
author: 'japicraft'
version: '${project.version}'
main: cc.crystalcavernsdungeons.CrystalCavernsDungeons
api-version: '1.20'
commands:
  spawn:
    description: Teleport the player to the server's global spawn point.
    aliases: [lobby, hub]
  party:
    description: Used to create and manage a Dungeon Run party.
  crystalcaverns:
    description: Main plugin command.
    aliases: [cc]
    permission: crystalcaverns.command